### ISSUE TITLE
Class 'App\Providers\App\Nova\User' not found

### ISSUE THREAD

**Issue by trueman52** [Sparclex/nova-import-card#14]
Returned error: Class 'App\Providers\App\Nova\User' not found

After default Laravel Nova installation
Then installing package via composer:
"composer require sparclex/nova-import-card"

Then registering in "NovaServiceProvider.php" file

public function card()
{
    return [
        // ...
        new \Sparclex\NovaImportCard\NovaImportCard(App\Nova\User::class),
    ];
}

Application returned error:

Class 'App\Providers\App\Nova\User' not found

In vendor\sparclex\nova-import-card\src\NovaImportCard.php
===================================
     */
    public $width = '1/2';
 
    public function __construct($resource)
    {
        parent::__construct();
        $this->withMeta([
            'fields' => [
                new File('File'),
            ],
            'resourceLabel' => $resource::label(),// --- This line returned error
=================================
![laravelnovaimportcard](https://user-images.githubusercontent.com/17707896/48859101-dc96a300-edc5-11e8-8750-fc68e8d59125.png)
![laravelnovaimportcard](https://user-images.githubusercontent.com/17707896/48859114-e3251a80-edc5-11e8-978d-b185e7c519d5.png)

**Comment by Sparclex** [comment]
Hi @trueman52 

If you replace `new \Sparclex\NovaImportCard\NovaImportCard(App\Nova\User::class),` with `new \Sparclex\NovaImportCard\NovaImportCard(\App\Nova\User::class),` you should be fine. You only forgot the backlash in front of the `App\Nova\User::class` and therefore php is looking for a class relatively to your current namespace which seems to be `App\Providers`


Please let me know if this fixes the issue.

Regards 

Silvan

**Comment by trueman52** [comment]
Thank you very much, Silvan!!! 

Problem solved!

And big thanks for your time regarding this Nova package. 

It can save a lot of time.
