### ISSUE TITLE
problem importing if there is 'belongsto' field in nova resource

### ISSUE THREAD

**Issue by fakhrikbr** [Sparclex/nova-import-card#15]
the value from belongsto field is always considered empty. why?

**Comment by Sparclex** [comment]
@fakhrikbr thanks for reporting your issue. 

Could you provide some more information to reconstruct the problem?

**Comment by fakhrikbr** [comment]
thank you for your respones :))

i have this code in my item resource:
```php
 public function fields(Request $request)
    {
        return [
            ID::make('ID*','id')->sortable()->rules('required','max:20'),
            Text::make('Name*','name')->rules('required','max:100'),
            BelongsTo::make('UOM ID*','unitOfMeasure',UnitOfMeasure::class)->rules('required'),
            BelongsTo::make('Item Category ID','itemCategory',ItemCategory::class)->nullable(),
            Text::make('Shelf No')->rules('max:30'),
            Image::make('Picture'),
            Text::make('Barcode No')->rules('max:20'),
            BelongsTo::make('Production BOM ID','productionBom',ProductionBom::class)->nullable(),
            BelongsTo::make('Routing Header ID','routingHeader',RoutingHeader::class)->nullable(),
            Boolean::make('Inventory Tracking'),
            Boolean::make('Scan Input Required'),
            BelongsTo::make('Company ID','company',Company::class)->nullable()
        ];
    }
```

and because unitOfMeasure is required field, it always give me message like this even though in my excel file, unitOfMeasure have a data.
![item err](https://user-images.githubusercontent.com/22675816/50801546-d3cb4380-1317-11e9-9aa1-23cdaa867942.JPG)

**Comment by fakhrikbr** [comment]
sorry for my bad english language hehe. i hope you understand with my info.

**Comment by fakhrikbr** [comment]
this is my code in pict

![code](https://user-images.githubusercontent.com/22675816/50801709-a337d980-1318-11e9-9b86-7247aecdf110.JPG)

**Comment by Sparclex** [comment]
Could you also provide your import file. Especially row 2 seems interesting, since there the error occurs.


Markdown supports syntax highlighting, just use three backticks instead of one see here: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

Just for future issues ;)

**Comment by fakhrikbr** [comment]
this is my import file and my unitOfMeasure data
![image](https://user-images.githubusercontent.com/22675816/50836819-bbe1d700-138c-11e9-87d2-2aa969dab193.png)

**Comment by fakhrikbr** [comment]
sorry for my wrong syntax highlightning before :)

**Comment by axlot** [comment]
Hello, I can confirm this issue. The belongsto field is not recognised and always returns an error saying that the field is not present.

Steps to reproduce.

1. Have a resource with a belongsTo field
2. Add the importer card to that same resource.
3. Import a file with all the columns and use the name of the field used on one as the name of the column and with the id of the related entity.

Expected result> data is imported
Actual result > error message saying "There was an error on row 2. The {{belongsTo}} field is required."

**Comment by axlot** [comment]
@fakhrikbr you need to put as the column name the same name used for the field, in the belongsto fields you need to put the relationship as the name. 

in your case you need to put unitsOfMeasure instead of UOM ID*

**Comment by fakhrikbr** [comment]
@axlot I've tried it before, but doesn't work. i've tried put UnitOfMeasure, uom_id like in my database field too. And still doesn't works.

**Comment by fakhrikbr** [comment]
btw, this is my items table schema

![image](https://user-images.githubusercontent.com/22675816/50939348-052a4780-14af-11e9-9733-d789449ff79b.png)

**Comment by fakhrikbr** [comment]
@axlot I've tried it before, but doesn't work. I've tried put UnitOfMeasure, unit_of_measure_id like in my database field too. And still doesn't works.

btw, this is my items table schema.

![image](https://user-images.githubusercontent.com/22675816/50939413-52a6b480-14af-11e9-9d16-a4abab1e883d.png)

**Comment by fakhrikbr** [comment]
ohiya, thanks for your response @axlot

**Comment by Sparclex** [comment]
So is there still an issue or did you resolve it?

**Comment by fakhrikbr** [comment]
Still an isssue. I can't resolve it yet till now, please help :)

**Comment by fakhrikbr** [comment]
Response from @axlot is not solution for my issue

**Comment by Sparclex** [comment]
Your column should have the same name as your relationship method. Did you put `UnitOfMeasure` or `unitOfMeasure`?

**Comment by fakhrikbr** [comment]
yes of course, like this.
![image](https://user-images.githubusercontent.com/22675816/51890259-358a4500-23ce-11e9-9709-802e1a3bec98.png)

but I still get errors

**Comment by Sparclex** [comment]
I cannot reproduce this error. Does it still exist with nova 2.0 and the newest version?
