### ISSUE TITLE
Card fields not respected

### ISSUE THREAD

**Issue by iSWORD** [Sparclex/nova-import-card#18]
I have a situation where I wish to include an additional field in the card, but it seems that even though there was [an intention](https://github.com/Sparclex/nova-import-card/blob/master/src/NovaImportCard.php#L21) to support customizing fields using a 'fields' meta field, it doesn't seem to be respected in [the view](https://github.com/Sparclex/nova-import-card/blob/master/resources/js/components/Card.vue#L8).

Is anyone working on this?

**Comment by Sparclex** [comment]
No but I would be happy to accept a PR for this.
