### ISSUE TITLE
Issue on file uploading.

### ISSUE THREAD

**Issue by bissolli** [Sparclex/nova-import-card#19]
**Nova Version: 1.3.1**

Hi guys,

I'm facing the following issue when trying to import an excel file.
![image](https://user-images.githubusercontent.com/1808444/52257886-38d58180-2936-11e9-9d3f-56e77ac1c87a.png)

Anyone with same problem? I didn't customized anything, just using the standard process.

Thanks!

**Comment by ragingdave** [comment]
same issue here although I don't even get the error, but also happening in Queued Importing.
`InvalidArgumentException: File "/tmp/N0VCdvlDyuK4K8os/php8GfTgI" does not exist. in /var/www/html/project/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Shared/File.php:137`

**Comment by Sparclex** [comment]
I cannot reproduce this error. Does it still exist in nova 2.0 and the newest version?
