### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by patricktsg** [Sparclex/nova-import-card#23]
![Screen Shot 2019-04-01 at 18 34 23](https://user-images.githubusercontent.com/16956839/55347440-d2d82700-54ac-11e9-9bea-34ed3674b372.png)
Happens after selecting the CSV file and hitting import - I have the card registered ona  Product resource as such:

`new \Sparclex\NovaImportCard\NovaImportCard(Product::class),`

Note: the docs say to reference the class through App\Nova\Model::class but this seems to repeat the App\Nova\App\Nova

**Comment by acewebsa** [comment]
Did you work out a way around this? I'm getting the same issue occurring.

Using
`new NovaImportCard(Blog::class),`

**Comment by patricktsg** [comment]
No sadly, just gave up on it - will build my own solution soon.

**Comment by Sparclex** [comment]
If you provide the full stack trace (shown in the console), the csv file, and the nova resource class I might be able to help you

Thank you for telling the issue with the documentation, I updated the readme.
