### ISSUE TITLE
Display all validation messages

### ISSUE THREAD

**Issue by Sparclex** [Sparclex/nova-import-card#3]
At the moment only one validation message is displayed due to the constraints of the card height. It should be possible to view all validation errors as mentioned in https://github.com/Sparclex/nova-import-card/issues/1#issuecomment-424302921

**Comment by kombimedia** [comment]
@Sparclex 
Hi mate. If haven't managed to get this working yet you could take a look at 'Nova Laravel Update Card'. This card adjusts it's height according to the the card content.

Hope that helps.

Cheers

**Comment by Sparclex** [comment]
closed with b1e59c4
