### ISSUE TITLE
Relateable rule

### ISSUE THREAD

**Issue by happyDemon** [Sparclex/nova-import-card#5]
There's an issue, if you allow for relations to be set during import.

`Laravel\Nova\Rules\Relatable:49` -> `$this->query->select('*')->whereKey($value)->first()`
The query doesn't ever reset, so on the second row being added it will keep adding another primary key check like this: `where `id` = ? and `id` = ?`.

This makes it fail

**Comment by Sparclex** [comment]
@happyDemon thanks for your feedback and your pull request. Could you show me your resources and your import for which this issue occurs?

**Comment by happyDemon** [comment]
@Sparclex It's easy to reproduce, try setting a belongsTo field during import.

**Comment by Sparclex** [comment]
Thanks its implemented now.
